---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enshrouded-k8s.fullname" . }}
  labels:
    {{- include "enshrouded-k8s.labels" . | nindent 4 }}
data:
  TZ: "{{ .Values.tz }}"
  SERVER_NAME: "{{ regexReplaceAll "\\W+" (default (printf "%s_%s" "enshrouded" (randAlphaNum 6 | nospace)) .Values.gameServer.serverName) "_" }}"
  SERVER_SLOT_COUNT: "{{ .Values.gameServer.players | int }}"
  SERVER_IP: "{{ .Values.gameServer.serverIP }}"
  SERVER_SAVE_DIR: "{{ .Values.gameServer.saveDir }}"
  SERVER_LOG_DIR: "{{ .Values.gameServer.logDir }}"
  UPDATE_CRON: "{{ .Values.gameServer.update.cron_expression }}"
  UPDATE_CHECK_PLAYERS: "{{ .Values.gameServer.update.check_players }}"
  BACKUP_CRON: "{{ .Values.gameServer.backup.cron_expression }}"
  BACKUP_DIR: "{{ .Values.gameServer.backup.directory }}"
  BACKUP_MAX_COUNT: "{{ .Values.gameServer.backup.max_count }}"
  GAME_BRANCH: "{{ .Values.gameServer.gameBranch }}"
  STEAMCMD_ARGS: "{{ .Values.gameServer.steamcmdArgs }}"
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: "{{ $value }}"
  {{- end }}