---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enshrouded-k8s.fullname" . }}
  labels:
    {{- include "enshrouded-k8s.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "enshrouded-k8s.selectorLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "enshrouded-k8s.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "enshrouded-k8s.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default (printf "%s-proton" .Chart.AppVersion) .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "enshrouded-k8s.fullname" . }}
          env:
            - name: SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "enshrouded-k8s.fullname" .) .Values.gameServer.existingSecret | quote }}
                  key: server-password
            {{- range $index, $role := $.Values.gameServer.roles }}
            - name: SERVER_ROLE_{{ $index }}_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "enshrouded-k8s.fullname" $) $.Values.gameServer.existingSecret | quote }}
                  key: {{ $role.name }}-password
            {{- end }}
          ports:
            - name: queryport
              containerPort: 15637
              protocol: UDP
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - mountPath: /opt/enshrouded
              name: datadir
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: datadir
          persistentVolumeClaim:
            {{- if not .Values.persistence.existingClaim }}
            claimName: {{ include "enshrouded-k8s.fullname" . }}
            {{ else }}
            claimName: "{{ .Values.persistence.existingClaim }}"
            {{- end }}
      {{- end }}