{{- if (not .Values.gameServer.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enshrouded-k8s.fullname" . }}
  labels:
    {{- include "enshrouded-k8s.labels" . | nindent 4 }}
type: Opaque
data:
  server-password: {{ default (randAlphaNum 12) .Values.gameServer.password | b64enc | quote }}
{{- end }}
