---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "enshrouded-k8s.fullname" . }}
  labels:
    {{- include "enshrouded-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: queryport
      port: {{ .Values.gameServer.service.port | int }}
      protocol: UDP
      targetPort: queryport
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "" .Values.gameServer.service.nodePort | int }}
      {{- end }}
  selector: 
    {{- include "enshrouded-k8s.selectorLabels" . | nindent 4 }}
